services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
  otel-lgtm:
    extends:
      file: .config/docker-compose-base.yaml
      service: otel-lgtm
  alloy:
    extends:
      file: .config/docker-compose-base.yaml
      service: alloy

